#--- MySQL DB Configuration ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#--JPA settings
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#---Optional
spring.application.name=eventapp
server.port=8080

jwt.secret=${JWT_SECRET}

#email authentication
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.frontend.base-url=http://localhost:3000

dotenv.system-properties=true

app.contact.to=${CONTACT_EMAIL:test@example.com}
