#--- MySQL DB Configuration ---
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/mydb
spring.datasource.username=root
spring.datasource.password=Ak636595.

#--JPA settings
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#---Optional
spring.application.name=eventapp
server.port=8080

jwt.secret=r+qHhd6vjOj0EFZs1ryuVpJ3mmbR5sf1WEXi/XmMNlE=

#email authentication
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gogreenerinfo@gmail.com
spring.mail.password=azdrkghamblgdepc 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.frontend.base-url=http://localhost:3000
