#--- DB Configuration (PostgreSQL) ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:3}
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

#--JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#---Optional
spring.application.name=eventapp
server.port=8080

jwt.secret=${JWT_SECRET}

#email authentication
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.frontend.base-url=https://www.gogreener.gr,https://gogreener.gr

dotenv.system-properties=true

app.contact.to=${CONTACT_EMAIL:test@example.com}
